[package]
name = "typed-html-iron-test"
version = "0.1.0"
edition = "2018"
authors = ["Bodil Stokke <bodil@bodil.org>"]

[dependencies]
typed-html-macros = { path = "../../macros" }
typed-html = { path = "../../typed-html" }
iron = "0.6.0"
