[package]
name = "typed-html-rocket-test"
version = "0.1.0"
authors = ["Bodil Stokke <bodil@bodil.org>"]

[dependencies]
typed-html-macros = { path = "../../macros" }
typed-html = { path = "../../typed-html" }
rocket = "0.4.0-rc.1"
